CREATE TABLE orders (
        'ID' INTEGER PRIMARY KEY,
        'FECHA' DATE,
        'MES' TEXT,
        'AÑO' INTEGER,
        'CLIENTE' TEXT,
        'PEDIDO #' TEXT,
        'REFERENCIA' TEXT,
        'COLOR' TEXT,
        'TALLAS' TEXT,
        'CANTIDAD' INTEGER,
        'PRECIO UND' REAL,
        'PRECIO TOTAL' REAL,
        'LINEA' TEXT,
        'MARCA' TEXT,
        'COLECCION' TEXT,
        'VENDEDOR' TEXT,
        'COSTO' REAL,
        'COSTO TOTAL' REAL,
        'ESTADO' TEXT
        );



SELECT FECHA, CLIENTE, REFERENCIA, COLOR, SUM(CANTIDAD) FROM orders
WHERE FECHA > "2021-08-01"
GROUP BY FECHA, CLIENTE, REFERENCIA, COLOR;

TRANSFORM SUM(CANTIDAD) as total
SELECT FECHA, CLIENTE, REFERENCIA, COLOR FROM orders
WHERE FECHA > "2021-08-01"
GROUP BY FECHA, CLIENTE, REFERENCIA, COLOR
PIVOT TALLAS;
