# Generated by Django 3.2.9 on 2021-11-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('customer', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('agent', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['id_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id_product_order', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, verbose_name='Referencia')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('size', models.CharField(max_length=5, verbose_name='Talla')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('line', models.CharField(max_length=30, verbose_name='Linea')),
                ('brand', models.CharField(max_length=30, verbose_name='Marca')),
                ('collection', models.CharField(max_length=40, verbose_name='Colección')),
                ('status', models.CharField(max_length=150, verbose_name='Estado')),
                ('price', models.FloatField(verbose_name='Precio Unidad')),
                ('total_price', models.FloatField(verbose_name='Precio Total')),
                ('cost', models.FloatField(verbose_name='Costo Unidad')),
                ('total_cost', models.FloatField(verbose_name='Costo Total')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='ID Pedido')),
            ],
            options={
                'verbose_name': 'ProductOrder',
                'verbose_name_plural': 'ProductsOrder',
                'db_table': 'products_order',
                'ordering': ['id_product_order'],
            },
        ),
    ]
