# Generated by Django 3.2.9 on 2021-11-04 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('customer', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('agent', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['id_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id_product_order', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('quantity', models.IntegerField()),
                ('line', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('collection', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'ProductOrder',
                'verbose_name_plural': 'ProductsOrder',
                'db_table': 'products_order',
                'ordering': ['id_product_order'],
            },
        ),
    ]
