# Generated by Django 3.2.9 on 2021-11-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
