# Generated by Django 3.2.9 on 2022-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.CharField(max_length=100, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo elctronico'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de Archivo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_order',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
